version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - misspell
    - errorlint
    - nilerr
    - gocritic
    - exhaustive

  settings:
    misspell:
      locale: US
    exhaustive:
      default-signifies-exhaustive: true

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
