package registry

import (
	"fmt"
	"os"
	"sort"
	"time"

	"github.com/securacore/codectx/core/project"
	"gopkg.in/yaml.v3"
)

// LockFileName is the filename for the lock file within the documentation root.
const LockFileName = "codectx.lock"

// LockVersion is the current lock file schema version.
const LockVersion = 1

// lockHeader is the comment header written at the top of codectx.lock files.
const lockHeader = "# codectx.lock\n# Auto-generated by codectx install. Do not edit manually.\n\n"

// SourceDirect indicates a package was directly declared in codectx.yml.
const SourceDirect = "direct"

// SourceTransitive indicates a package was pulled in by another dependency.
const SourceTransitive = "transitive"

// LockFile represents the codectx.lock schema.
// It captures the full flattened dependency tree with exact resolved versions.
// Checked into version control for deterministic reproducibility.
type LockFile struct {
	// LockfileVersion is the schema version (currently 1).
	LockfileVersion int `yaml:"lockfile_version"`

	// ResolvedAt is the ISO 8601 timestamp of when resolution was performed.
	ResolvedAt string `yaml:"resolved_at"`

	// Packages maps "name@org" to the locked package details.
	Packages map[string]*LockedPackage `yaml:"packages"`
}

// LockedPackage represents a single resolved package in the lock file.
type LockedPackage struct {
	// ResolvedVersion is the exact semver version that was resolved.
	ResolvedVersion string `yaml:"resolved_version"`

	// Repo is the full GitHub repository path (e.g. "github.com/community/codectx-react-patterns").
	Repo string `yaml:"repo"`

	// Commit is the git commit SHA for the resolved version tag.
	Commit string `yaml:"commit"`

	// Source is "direct" or "transitive".
	Source string `yaml:"source"`

	// RequiredBy lists which packages require this transitive dependency.
	// Only populated for transitive packages. Each entry is "name@org:version".
	RequiredBy []string `yaml:"required_by,omitempty"`
}

// NewLockFile creates an empty lock file with the current schema version
// and timestamp.
func NewLockFile() *LockFile {
	return &LockFile{
		LockfileVersion: LockVersion,
		ResolvedAt:      time.Now().UTC().Format(time.RFC3339),
		Packages:        make(map[string]*LockedPackage),
	}
}

// LoadLock reads and parses a codectx.lock file.
func LoadLock(path string) (*LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading lock file: %w", err)
	}

	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("parsing lock file: %w", err)
	}

	if lf.Packages == nil {
		lf.Packages = make(map[string]*LockedPackage)
	}

	return &lf, nil
}

// SaveLock writes the lock file to disk with 2-space YAML indentation.
func SaveLock(path string, lf *LockFile) error {
	return project.WriteYAMLFile(path, lockHeader, lf)
}

// LockCurrent checks whether the lock file is up-to-date with the
// dependencies declared in codectx.yml. Returns true if every dependency
// key in cfg.Dependencies has a corresponding entry in the lock file.
//
// This is a fast check — it does NOT verify that resolved versions are
// still the latest. Use codectx update for that.
func LockCurrent(lf *LockFile, deps map[string]*project.DependencyConfig) bool {
	for key := range deps {
		dk, err := ParseDepKey(key)
		if err != nil {
			return false
		}
		ref := dk.PackageRef()
		if _, ok := lf.Packages[ref]; !ok {
			return false
		}
	}
	return true
}

// SortedPackageRefs returns the lock file package references in sorted order.
// Used for deterministic output rendering.
func (lf *LockFile) SortedPackageRefs() []string {
	refs := make([]string, 0, len(lf.Packages))
	for ref := range lf.Packages {
		refs = append(refs, ref)
	}
	sort.Strings(refs)
	return refs
}
