// Package taxonomy implements the taxonomy extraction pipeline for codectx.
//
// The taxonomy is a compiled artifact derived from source documentation.
// It serves as a controlled vocabulary with aliases that bridges the gap
// between how developers phrase queries and how documentation uses
// terminology.
//
// The extraction pipeline runs in four passes:
//
//  1. Structural term extraction (pure parsing, no NLP): headings, code
//     identifiers, bold/emphasized terms, structured positions.
//  2. POS-based term extraction (lightweight NLP via prose): noun phrases,
//     named entities, compound terms. Optional, controlled by POSExtraction
//     preference.
//  3. Deduplication and normalization: merge duplicates from all passes,
//     score by frequency, filter by min_term_frequency threshold. Runs
//     before relationship inference so that only surviving terms get
//     relationships assigned.
//  4. Relationship inference (structural analysis): heading hierarchy yields
//     parent/child, cross-references yield lateral relationships.
//
// The data model is inspired by W3C SKOS (Simple Knowledge Organization
// System): each term has a canonical label (prefLabel), alternative labels
// (altLabel), and broader/narrower/related relationships.
package taxonomy

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/securacore/codectx/core/project"
)

// taxonomyFile is the output filename for the taxonomy.
const taxonomyFile = "taxonomy.yml"

// taxonomyHeader is the comment header written at the top of taxonomy.yml.
const taxonomyHeader = "# codectx compiled taxonomy\n# Controlled vocabulary with hierarchical relationships.\n# Generated by codectx compile \u2014 do not edit.\n\n"

// Source constants identify how a term was discovered.
const (
	SourceHeading            = "heading"
	SourceCodeIdentifier     = "code_identifier"
	SourceBoldTerm           = "bold_term"
	SourceStructuredPosition = "structured_position"
	SourcePOS                = "pos_extraction"
	SourceCorpusAbbreviation = "corpus_abbreviation"
	SourceDictionary         = "dictionary"
)

// Taxonomy is the top-level structure for taxonomy.yml.
type Taxonomy struct {
	// Encoding is the tokenizer encoding used (e.g. "cl100k_base").
	Encoding string `yaml:"encoding"`

	// CompiledWith is the LLM model used for taxonomy augmentation.
	// Empty until LLM augmentation (Step 11) populates it.
	CompiledWith string `yaml:"compiled_with,omitempty"`

	// CompiledAt is the ISO 8601 timestamp of compilation.
	CompiledAt string `yaml:"compiled_at"`

	// InstructionsHash is the SHA-256 hash of the
	// system/topics/taxonomy-generation/ directory. A change triggers
	// full taxonomy regeneration on incremental builds.
	InstructionsHash string `yaml:"instructions_hash"`

	// TermCount is the total number of canonical terms.
	TermCount int `yaml:"term_count"`

	// Terms maps normalized term keys to their definitions.
	Terms map[string]*Term `yaml:"terms"`
}

// Term represents a single entry in the taxonomy.
type Term struct {
	// Canonical is the preferred display label (SKOS prefLabel).
	Canonical string `yaml:"canonical"`

	// Aliases are alternative labels (SKOS altLabel).
	// Empty until LLM augmentation (Step 11) populates them.
	Aliases []string `yaml:"aliases,omitempty"`

	// Broader is the parent term key in the hierarchy, or empty for top-level.
	Broader string `yaml:"broader,omitempty"`

	// Narrower lists child term keys in the hierarchy.
	Narrower []string `yaml:"narrower,omitempty"`

	// Related lists lateral (non-hierarchical) related term keys.
	Related []string `yaml:"related,omitempty"`

	// Chunks lists the chunk IDs where this term appears.
	Chunks []string `yaml:"chunks"`

	// Source is the discovery method (heading, code_identifier, bold_term,
	// structured_position). When a term is discovered by multiple methods,
	// the highest-confidence source wins (heading > code > bold > structured).
	Source string `yaml:"source"`
}

// sourceRank returns a priority rank for a source type.
// Lower values indicate higher confidence.
func sourceRank(source string) int {
	switch source {
	case SourceHeading:
		return 0
	case SourceCodeIdentifier:
		return 1
	case SourceBoldTerm:
		return 2
	case SourceStructuredPosition:
		return 3
	case SourcePOS:
		return 4
	case SourceCorpusAbbreviation:
		return 5
	case SourceDictionary:
		return 6
	default:
		return 7
	}
}

// WriteTo serializes the taxonomy to YAML at the given path.
func (t *Taxonomy) WriteTo(path string) error {
	return project.WriteYAMLFile(path, taxonomyHeader, t)
}

// TaxonomyPath returns the path to the taxonomy file within the compiled directory.
func TaxonomyPath(compiledDir string) string {
	return filepath.Join(compiledDir, taxonomyFile)
}

// Load reads and parses the taxonomy YAML file at the given path.
func Load(path string) (*Taxonomy, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading taxonomy: %w", err)
	}

	var t Taxonomy
	if err := yaml.Unmarshal(data, &t); err != nil {
		return nil, fmt.Errorf("parsing taxonomy: %w", err)
	}

	if t.Terms == nil {
		t.Terms = make(map[string]*Term)
	}

	return &t, nil
}

// slugSep matches characters that should become hyphens in slugs.
var slugSep = regexp.MustCompile(`[^a-z0-9]+`)

// leadTrailHyphen matches leading or trailing hyphens.
var leadTrailHyphen = regexp.MustCompile(`^-+|-+$`)

// NormalizeKey converts a term string into a normalized slug key.
//
// Rules:
//   - Lowercase
//   - Non-alphanumeric characters become hyphens
//   - Leading/trailing hyphens stripped
//   - Consecutive hyphens collapsed
//
// Examples: "JWT Tokens" -> "jwt-tokens", "Error Handling" -> "error-handling".
func NormalizeKey(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = slugSep.ReplaceAllString(s, "-")
	s = leadTrailHyphen.ReplaceAllString(s, "")
	return s
}

// AliasIndex is a reverse index mapping lowercased aliases and canonical
// names to their term keys. Used for query expansion: given a query token,
// look up which taxonomy term(s) it maps to.
type AliasIndex struct {
	// lookup maps a lowercased alias or canonical to term key.
	lookup map[string]string
}

// BuildAliasIndex constructs a reverse alias index from the taxonomy.
// For each term, both the canonical name (lowercased) and all aliases
// are mapped to the term key. If two terms share an alias, the first
// one encountered wins (stable by sorted key order).
func BuildAliasIndex(tax *Taxonomy) *AliasIndex {
	ai := &AliasIndex{
		lookup: make(map[string]string, len(tax.Terms)*3),
	}

	// Sort keys for deterministic behavior.
	keys := make([]string, 0, len(tax.Terms))
	for k := range tax.Terms {
		keys = append(keys, k)
	}
	sortStrings(keys)

	for _, key := range keys {
		term := tax.Terms[key]

		// Map the canonical name (lowercased).
		canonical := strings.ToLower(term.Canonical)
		if _, exists := ai.lookup[canonical]; !exists {
			ai.lookup[canonical] = key
		}

		// Map each alias.
		for _, alias := range term.Aliases {
			lower := strings.ToLower(alias)
			if _, exists := ai.lookup[lower]; !exists {
				ai.lookup[lower] = key
			}
		}

		// Map the key itself (it's already normalized/lowercase).
		if _, exists := ai.lookup[key]; !exists {
			ai.lookup[key] = key
		}
	}

	return ai
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// LookupByAlias returns the term key that matches the given alias or
// canonical name (case-insensitive). Returns empty string if no match.
func (ai *AliasIndex) LookupByAlias(alias string) string {
	return ai.lookup[strings.ToLower(alias)]
}

// lookupTerm returns the full Term for a given alias/canonical, or nil if
// no match exists. Requires the taxonomy to resolve the key.
func (ai *AliasIndex) lookupTerm(alias string, tax *Taxonomy) *Term {
	key := ai.LookupByAlias(alias)
	if key == "" {
		return nil
	}
	return tax.Terms[key]
}
