package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/securacore/codectx/core/markdown"
	"github.com/securacore/codectx/core/project"
)

// hashesHeader is the comment header written at the top of hashes.yml.
const hashesHeader = "# codectx content hashes\n# Content hashes for incremental compilation and cache invalidation.\n# Generated by codectx compile \u2014 do not edit.\n\n"

// hashPrefix is prepended to hex digests in the output (e.g. "sha256:abc123...").
const hashPrefix = "sha256:"

// systemInstructionDirs lists the system instruction subdirectory names whose
// hashes are tracked individually in hashes.yml for incremental compilation.
// Each name corresponds to a directory under docs/system/topics/.
var systemInstructionDirs = []string{
	"context-assembly",
}

// SystemInstructionDirs returns a copy of the tracked system instruction
// directory names. Returns a copy to prevent callers from mutating the
// internal list.
func SystemInstructionDirs() []string {
	out := make([]string, len(systemInstructionDirs))
	copy(out, systemInstructionDirs)
	return out
}

// HashSystemDirs computes per-subdirectory hashes for system instruction directories.
// The topicsDir parameter is the absolute path to the system/topics/ directory.
// Returns a map from directory name to "sha256:<hex>" hash.
// Directories that do not exist are silently skipped.
func HashSystemDirs(topicsDir string) (map[string]string, error) {
	hashes := make(map[string]string, len(systemInstructionDirs))
	for _, name := range systemInstructionDirs {
		dirPath := filepath.Join(topicsDir, name)
		info, err := os.Stat(dirPath)
		if err != nil || !info.IsDir() {
			continue
		}
		h, err := HashDir(dirPath)
		if err != nil {
			return nil, fmt.Errorf("hashing system directory %q: %w", name, err)
		}
		hashes[name] = h
	}
	return hashes, nil
}

// Hashes is the top-level structure for hashes.yml.
// It tracks content hashes for every source file and system instruction
// directory, enabling incremental compilation.
type Hashes struct {
	// CompiledAt is the ISO 8601 timestamp of when hashes were computed.
	CompiledAt string `yaml:"compiled_at"`

	// Files maps relative source file paths to their "sha256:<hex>" content hashes.
	Files map[string]string `yaml:"files"`

	// System maps system instruction directory names (e.g. "context-assembly")
	// to their "sha256:<hex>" hashes. Used for incremental compilation
	// cache invalidation when system documentation changes.
	System map[string]string `yaml:"system"`
}

// BuildHashes constructs a Hashes from precomputed file and system directory hashes.
//
// Both parameters map names to "sha256:<hex>" formatted hash strings.
// Pass nil for either if no entries exist.
func BuildHashes(files map[string]string, systemDirs map[string]string) *Hashes {
	h := &Hashes{
		CompiledAt: CompiledAtNow(),
		Files:      files,
		System:     systemDirs,
	}
	if h.Files == nil {
		h.Files = make(map[string]string)
	}
	if h.System == nil {
		h.System = make(map[string]string)
	}
	return h
}

// HashFile computes a SHA-256 hash of a file's contents.
// Returns the hash in "sha256:<hex>" format.
func HashFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading file %q: %w", path, err)
	}
	return hashPrefix + markdown.Hash(data), nil
}

// HashDir computes a deterministic SHA-256 hash of a directory's contents.
// It walks all files in sorted order, hashes each file individually,
// concatenates the hex hashes, and SHA-256s the result.
//
// Only regular files are included (subdirectories are walked recursively).
// Returns the hash in "sha256:<hex>" format.
// Returns an error if the directory does not exist or cannot be read.
func HashDir(dirPath string) (string, error) {
	var hashes []string

	err := filepath.WalkDir(dirPath, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("reading %q: %w", path, readErr)
		}

		hashes = append(hashes, markdown.Hash(data))
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("walking directory %q: %w", dirPath, err)
	}

	if len(hashes) == 0 {
		// Empty directory — hash of empty string.
		return hashPrefix + markdown.Hash(nil), nil
	}

	// Sort for determinism (filepath.WalkDir already sorts, but be explicit).
	sort.Strings(hashes)

	// Concatenate all hex hashes and hash the result.
	combined := strings.Join(hashes, "")
	return hashPrefix + markdown.Hash([]byte(combined)), nil
}

// WriteTo serializes the hashes to YAML at the given path.
func (h *Hashes) WriteTo(path string) error {
	return project.WriteYAMLFile(path, hashesHeader, h)
}

// HashesPath returns the path to the hashes file within the compiled directory.
func HashesPath(compiledDir string) string {
	return filepath.Join(compiledDir, HashesFile)
}
