package manifest

import (
	"path/filepath"

	"github.com/securacore/codectx/core/index"
	"github.com/securacore/codectx/core/project"
)

// heuristicsHeader is the comment header written at the top of heuristics.yml.
const heuristicsHeader = "# codectx compilation heuristics\n# Diagnostic report of the compilation pipeline.\n# Generated by codectx compile \u2014 do not edit.\n\n"

// Heuristics is the top-level structure for heuristics.yml.
// It captures a snapshot of every compilation stage's output for
// diagnostic, incremental-cache, and AI-orientation purposes.
type Heuristics struct {
	// CompiledAt is the ISO 8601 timestamp of when compilation occurred.
	CompiledAt string `yaml:"compiled_at"`

	// CompilerVersion is the codectx version string (e.g. "0.1.0", "dev").
	CompilerVersion string `yaml:"compiler_version"`

	// Encoding is the tokenizer encoding used (e.g. "cl100k_base").
	Encoding string `yaml:"encoding"`

	// Sources summarizes the compilation input files.
	Sources *SourcesSection `yaml:"sources"`

	// Chunks summarizes the chunking output.
	Chunks *ChunksSection `yaml:"chunks"`

	// Taxonomy summarizes taxonomy extraction statistics.
	Taxonomy *TaxonomySection `yaml:"taxonomy"`

	// Session summarizes session context assembly.
	Session *SessionSection `yaml:"session"`

	// BM25 summarizes BM25 index statistics per index type.
	BM25 *BM25Section `yaml:"bm25"`

	// Incremental summarizes incremental compilation decisions.
	Incremental *IncrementalSection `yaml:"incremental"`

	// Timing records per-stage timing in seconds.
	Timing *TimingSection `yaml:"timing"`
}

// SourcesSection holds statistics about compilation input files.
type SourcesSection struct {
	TotalFiles   int `yaml:"total_files"`
	LocalFiles   int `yaml:"local_files"`
	PackageFiles int `yaml:"package_files"`
	New          int `yaml:"new"`
	Modified     int `yaml:"modified"`
	Unchanged    int `yaml:"unchanged"`
	SpecFiles    int `yaml:"spec_files"`
}

// ChunksSection holds statistics about chunk output.
type ChunksSection struct {
	Total         int `yaml:"total"`
	Objects       int `yaml:"objects"`
	Specs         int `yaml:"specs"`
	System        int `yaml:"system"`
	TotalTokens   int `yaml:"total_tokens"`
	AverageTokens int `yaml:"average_tokens"`
	MinTokens     int `yaml:"min_tokens"`
	MaxTokens     int `yaml:"max_tokens"`
	Oversized     int `yaml:"oversized"`
}

// TaxonomySection holds taxonomy extraction statistics.
type TaxonomySection struct {
	CanonicalTerms               int     `yaml:"canonical_terms"`
	TotalAliases                 int     `yaml:"total_aliases"`
	AverageAliasesPerTerm        float64 `yaml:"average_aliases_per_term"`
	TermsFromHeadings            int     `yaml:"terms_from_headings"`
	TermsFromCodeIdents          int     `yaml:"terms_from_code_identifiers"`
	TermsFromBoldTerms           int     `yaml:"terms_from_bold_terms"`
	TermsFromStructuredPositions int     `yaml:"terms_from_structured_positions"`
	TermsFromPOSExtraction       int     `yaml:"terms_from_pos_extraction"`
	CorpusAbbreviationPairs      int     `yaml:"corpus_abbreviation_pairs"`
	TermsWithCorpusAliases       int     `yaml:"terms_with_corpus_aliases"`
}

// SessionSection holds session context assembly statistics.
type SessionSection struct {
	TotalTokens int            `yaml:"total_tokens"`
	Budget      int            `yaml:"budget"`
	Utilization string         `yaml:"utilization"`
	Entries     []SessionEntry `yaml:"entries"`
}

// SessionEntry is a single entry in the session context listing.
type SessionEntry struct {
	Path   string `yaml:"path"`
	Tokens int    `yaml:"tokens"`
}

// BM25Section holds per-index-type BM25 statistics.
type BM25Section struct {
	Objects *BM25IndexStats `yaml:"objects"`
	Specs   *BM25IndexStats `yaml:"specs"`
	System  *BM25IndexStats `yaml:"system"`
}

// BM25IndexStats holds statistics for a single BM25 index.
type BM25IndexStats struct {
	IndexedTerms       int     `yaml:"indexed_terms"`
	IndexedChunks      int     `yaml:"indexed_chunks"`
	AverageChunkLength float64 `yaml:"average_chunk_length"`
}

// IncrementalSection holds incremental compilation details.
type IncrementalSection struct {
	FullRecompile             bool                       `yaml:"full_recompile"`
	StagesSkipped             []string                   `yaml:"stages_skipped"`
	StagesRerun               []string                   `yaml:"stages_rerun"`
	SystemInstructionsChanged *SystemInstructionsChanged `yaml:"system_instructions_changed"`
}

// SystemInstructionsChanged tracks which system instruction directories changed.
type SystemInstructionsChanged struct {
	ContextAssembly bool `yaml:"context_assembly"`
}

// TimingSection records per-stage timing in seconds.
type TimingSection struct {
	TotalSeconds       float64 `yaml:"total_seconds"`
	ParseValidate      float64 `yaml:"parse_validate"`
	StripNormalize     float64 `yaml:"strip_normalize"`
	Chunking           float64 `yaml:"chunking"`
	BM25Indexing       float64 `yaml:"bm25_indexing"`
	TaxonomyExtraction float64 `yaml:"taxonomy_extraction"`
	ManifestGeneration float64 `yaml:"manifest_generation"`
	ContextAssembly    float64 `yaml:"context_assembly"`
	SyncEntryPoints    float64 `yaml:"sync_entry_points"`
}

// NewHeuristics creates a Heuristics with required top-level fields
// and all sections initialized to zero-value defaults.
//
// The version parameter should be the compiler version string.
// The encoding parameter should be the tokenizer encoding name.
func NewHeuristics(version, encoding string) *Heuristics {
	return &Heuristics{
		CompiledAt:      CompiledAtNow(),
		CompilerVersion: version,
		Encoding:        encoding,
		Sources:         &SourcesSection{},
		Chunks:          &ChunksSection{},
		Taxonomy:        &TaxonomySection{},
		Session:         &SessionSection{},
		BM25:            &BM25Section{},
		Incremental: &IncrementalSection{
			SystemInstructionsChanged: &SystemInstructionsChanged{},
		},
		Timing: &TimingSection{},
	}
}

// SetSources populates the sources section.
func (h *Heuristics) SetSources(s *SourcesSection) {
	h.Sources = s
}

// SetChunkStats populates the chunks section.
func (h *Heuristics) SetChunkStats(c *ChunksSection) {
	h.Chunks = c
}

// SetBM25Stats populates the BM25 section from index statistics.
//
// The idx parameter is the compiled BM25 index; statistics are extracted
// for each index type (objects, specs, system).
func (h *Heuristics) SetBM25Stats(idx *index.Index) {
	toBM25 := func(s index.IndexStats) *BM25IndexStats {
		return &BM25IndexStats{
			IndexedTerms:       s.IndexedTerms,
			IndexedChunks:      s.IndexedChunks,
			AverageChunkLength: s.AvgChunkLength,
		}
	}

	h.BM25 = &BM25Section{
		Objects: toBM25(idx.Stats(index.IndexObjects)),
		Specs:   toBM25(idx.Stats(index.IndexSpecs)),
		System:  toBM25(idx.Stats(index.IndexSystem)),
	}
}

// SetSession populates the session context assembly section.
func (h *Heuristics) SetSession(totalTokens, budget int, utilization string, entries []SessionEntry) {
	h.Session = &SessionSection{
		TotalTokens: totalTokens,
		Budget:      budget,
		Utilization: utilization,
		Entries:     entries,
	}
}

// SetTaxonomyStats populates the taxonomy section with extraction statistics.
func (h *Heuristics) SetTaxonomyStats(tax *TaxonomySection) {
	h.Taxonomy = tax
}

// SetTiming populates the timing section.
func (h *Heuristics) SetTiming(timing *TimingSection) {
	h.Timing = timing
}

// SetIncremental populates the incremental compilation section.
func (h *Heuristics) SetIncremental(inc *IncrementalSection) {
	h.Incremental = inc
}

// WriteTo serializes the heuristics to YAML at the given path.
func (h *Heuristics) WriteTo(path string) error {
	return project.WriteYAMLFile(path, heuristicsHeader, h)
}

// HeuristicsPath returns the path to the heuristics file within the compiled directory.
func HeuristicsPath(compiledDir string) string {
	return filepath.Join(compiledDir, HeuristicsFile)
}
