package manifest

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/securacore/codectx/core/chunk"
	"github.com/securacore/codectx/core/project"
)

// manifestHeader is the comment header written at the top of manifest.yml.
const manifestHeader = "# codectx compiled manifest\n# Chunk navigation map with token counts, adjacency, and cross-references.\n# Generated by codectx compile \u2014 do not edit.\n\n"

// Manifest is the top-level structure for manifest.yml.
// It contains every compiled chunk grouped by type (objects, specs, system)
// with adjacency links, taxonomy term placeholders, and bridge summary
// placeholders.
type Manifest struct {
	// TotalChunks is the total number of chunks across all types.
	TotalChunks int `yaml:"total_chunks"`

	// TotalObjectChunks is the number of object (instruction) chunks.
	TotalObjectChunks int `yaml:"total_object_chunks"`

	// TotalSpecChunks is the number of spec (reasoning) chunks.
	TotalSpecChunks int `yaml:"total_spec_chunks"`

	// TotalSystemChunks is the number of system chunks.
	TotalSystemChunks int `yaml:"total_system_chunks"`

	// TotalTokens is the sum of all chunk token counts.
	TotalTokens int `yaml:"total_tokens"`

	// Encoding is the tokenizer encoding used for token counting.
	Encoding string `yaml:"encoding"`

	// BridgeInstructionsHash is the SHA-256 hash of the system/topics/bridge-summaries/
	// directory. A change triggers full bridge regeneration. Nil if not yet computed.
	BridgeInstructionsHash *string `yaml:"bridge_instructions_hash"`

	// Objects contains all instruction/documentation chunk entries keyed by chunk ID.
	Objects map[string]*ManifestEntry `yaml:"objects,omitempty"`

	// Specs contains all reasoning chunk entries keyed by chunk ID.
	Specs map[string]*ManifestEntry `yaml:"specs,omitempty"`

	// System contains all system/compiler chunk entries keyed by chunk ID.
	System map[string]*ManifestEntry `yaml:"system,omitempty"`
}

// ManifestEntry describes a single chunk in the manifest.
type ManifestEntry struct {
	// Type is the chunk type string ("object", "spec", "system").
	Type string `yaml:"type"`

	// Source is the relative path of the source markdown file.
	Source string `yaml:"source"`

	// Heading is the heading breadcrumb at the chunk's position.
	Heading string `yaml:"heading"`

	// Sequence is the 1-based chunk index within the source file.
	Sequence int `yaml:"sequence"`

	// TotalInFile is the total number of chunks from this source file.
	TotalInFile int `yaml:"total_in_file"`

	// Tokens is the token count of the chunk content.
	Tokens int `yaml:"tokens"`

	// Terms is the list of taxonomy term keys for this chunk.
	// Populated by the taxonomy extraction stage during compilation.
	Terms []string `yaml:"terms"`

	// Adjacent describes the previous/next chunk within the same file.
	// Omitted for spec chunks (they link via ParentObject instead).
	Adjacent *Adjacency `yaml:"adjacent,omitempty"`

	// BridgeToNext is a summary bridging this chunk to the next.
	// Populated deterministically (heading transition + RAKE + last sentence),
	// then optionally overwritten by LLM augmentation if enabled.
	BridgeToNext *string `yaml:"bridge_to_next"`

	// SpecChunk is the ID of the corresponding spec chunk, if one exists.
	// Only set on object/system entries. Nil if no spec file covers this heading.
	SpecChunk *string `yaml:"spec_chunk,omitempty"`

	// ParentObject is the ID of the corresponding object chunk.
	// Only set on spec entries. Nil if no matching object chunk was found.
	ParentObject *string `yaml:"parent_object,omitempty"`
}

// BuildManifest constructs a Manifest from compiled chunks.
//
// It groups chunks by type, computes adjacency within each source file,
// and links spec chunks to their parent object chunks by heading alignment.
//
// The encoding parameter is the tokenizer encoding name (e.g. "cl100k_base").
// The bridgeHash parameter is the hash of the bridge-summaries system directory,
// or nil if not yet available.
// The chunkTerms parameter maps chunk IDs to taxonomy term keys. If nil,
// all entries will have nil Terms (pre-taxonomy behavior).
func BuildManifest(chunks []chunk.Chunk, encoding string, bridgeHash *string, chunkTerms map[string][]string) *Manifest {
	m := &Manifest{
		Encoding:               encoding,
		BridgeInstructionsHash: bridgeHash,
		Objects:                make(map[string]*ManifestEntry),
		Specs:                  make(map[string]*ManifestEntry),
		System:                 make(map[string]*ManifestEntry),
	}

	// Build entries and route to the correct map.
	for i := range chunks {
		c := &chunks[i]

		// Populate terms from taxonomy extraction, or nil if not available.
		var terms []string
		if chunkTerms != nil {
			terms = chunkTerms[c.ID]
		}

		entry := &ManifestEntry{
			Type:         string(c.Type),
			Source:       c.Source,
			Heading:      c.Heading,
			Sequence:     c.Sequence,
			TotalInFile:  c.TotalInFile,
			Tokens:       c.Tokens,
			Terms:        terms,
			BridgeToNext: nil, // Populated by deterministic + optional LLM bridges.
		}

		m.TotalTokens += c.Tokens

		switch c.Type {
		case chunk.ChunkSpec:
			// Spec chunks use ParentObject instead of Adjacent.
			entry.ParentObject = nil // Placeholder, linked below.
			m.Specs[c.ID] = entry
			m.TotalSpecChunks++
		case chunk.ChunkSystem:
			entry.Adjacent = &Adjacency{}
			m.System[c.ID] = entry
			m.TotalSystemChunks++
		default:
			entry.Adjacent = &Adjacency{}
			entry.SpecChunk = nil // Placeholder, linked below.
			m.Objects[c.ID] = entry
			m.TotalObjectChunks++
		}
	}

	m.TotalChunks = m.TotalObjectChunks + m.TotalSpecChunks + m.TotalSystemChunks

	// Compute adjacency for object and system chunks.
	computeAdjacency(m.Objects)
	computeAdjacency(m.System)

	// Link spec chunks to their parent object chunks.
	linkSpecsToObjects(m)

	return m
}

// computeAdjacency sets the previous/next fields for entries that share a
// source file. Entries are linked in sequence order within each file.
func computeAdjacency(entries map[string]*ManifestEntry) {
	// Group entries by source file.
	bySource := make(map[string][]entryRef)
	for id, e := range entries {
		bySource[e.Source] = append(bySource[e.Source], entryRef{id: id, entry: e})
	}

	for _, refs := range bySource {
		// Sort by sequence within each file.
		sort.Slice(refs, func(i, j int) bool {
			return refs[i].entry.Sequence < refs[j].entry.Sequence
		})

		for i := range refs {
			if i > 0 {
				refs[i].entry.Adjacent.Previous = StringPtr(refs[i-1].id)
			}
			if i < len(refs)-1 {
				refs[i].entry.Adjacent.Next = StringPtr(refs[i+1].id)
			}
		}
	}
}

// entryRef pairs a chunk ID with its manifest entry for sorting.
type entryRef struct {
	id    string
	entry *ManifestEntry
}

// linkSpecsToObjects links spec chunks to their parent object chunks and
// vice versa, using heading path alignment.
//
// For a spec file at "docs/topics/auth/jwt.spec.md", the parent object file
// is "docs/topics/auth/jwt.md". Spec chunks are matched to object chunks by
// finding the object chunk whose heading is the longest prefix match of the
// spec chunk's heading.
func linkSpecsToObjects(m *Manifest) {
	// Build a lookup of object chunks grouped by source file.
	objectsBySource := make(map[string][]entryRef)
	for id, e := range m.Objects {
		objectsBySource[e.Source] = append(objectsBySource[e.Source], entryRef{id: id, entry: e})
	}

	// Sort spec IDs for deterministic iteration order.
	specIDs := make([]string, 0, len(m.Specs))
	for id := range m.Specs {
		specIDs = append(specIDs, id)
	}
	sort.Strings(specIDs)

	for _, specID := range specIDs {
		specEntry := m.Specs[specID]
		objectSource := specSourceToObjectSource(specEntry.Source)
		objectRefs, ok := objectsBySource[objectSource]
		if !ok {
			continue
		}

		// Sort object refs by sequence for deterministic tie-breaking.
		sort.Slice(objectRefs, func(i, j int) bool {
			return objectRefs[i].entry.Sequence < objectRefs[j].entry.Sequence
		})

		// Find the object chunk with the best heading match.
		// On equal match length, prefer the earlier sequence (first in sorted order).
		bestID := ""
		bestLen := -1

		for _, objRef := range objectRefs {
			matchLen := headingMatchLength(specEntry.Heading, objRef.entry.Heading)
			if matchLen > bestLen {
				bestLen = matchLen
				bestID = objRef.id
			}
		}

		if bestID != "" {
			specEntry.ParentObject = StringPtr(bestID)

			// Also set the reverse link on the object entry, but only if
			// it doesn't already have a spec_chunk assigned (first match wins).
			if objEntry, ok := m.Objects[bestID]; ok && objEntry.SpecChunk == nil {
				objEntry.SpecChunk = StringPtr(specID)
			}
		}
	}
}

// specSourceToObjectSource converts a .spec.md source path to its parent
// .md source path. E.g. "docs/topics/auth/jwt.spec.md" -> "docs/topics/auth/jwt.md".
func specSourceToObjectSource(specSource string) string {
	return strings.TrimSuffix(specSource, chunk.SpecFileSuffix) + ".md"
}

// headingMatchLength returns the length of the shared prefix between two
// heading breadcrumb strings. Used for aligning spec chunks to object chunks.
// Returns -1 if there is no match at all (empty or completely different).
func headingMatchLength(specHeading, objectHeading string) int {
	if specHeading == "" || objectHeading == "" {
		return -1
	}

	// Exact match is the strongest signal.
	if specHeading == objectHeading {
		return len(specHeading)
	}

	// Check if the object heading is a prefix of the spec heading.
	if strings.HasPrefix(specHeading, objectHeading) {
		return len(objectHeading)
	}

	// Check if the spec heading is a prefix of the object heading.
	if strings.HasPrefix(objectHeading, specHeading) {
		return len(specHeading)
	}

	// Find the longest common prefix by walking separator-delimited segments.
	specParts := strings.Split(specHeading, chunk.HeadingSeparator)
	objParts := strings.Split(objectHeading, chunk.HeadingSeparator)

	matchLen := 0
	sepLen := len(chunk.HeadingSeparator)
	for i := 0; i < len(specParts) && i < len(objParts); i++ {
		if specParts[i] != objParts[i] {
			break
		}
		if matchLen > 0 {
			matchLen += sepLen
		}
		matchLen += len(specParts[i])
	}

	if matchLen == 0 {
		return -1
	}
	return matchLen
}

// WriteTo serializes the manifest to YAML at the given path.
func (m *Manifest) WriteTo(path string) error {
	return project.WriteYAMLFile(path, manifestHeader, m)
}

// LookupEntry returns the ManifestEntry for a given chunk ID, searching
// across all three type maps. Returns nil if not found.
func (m *Manifest) LookupEntry(id string) *ManifestEntry {
	if e, ok := m.Objects[id]; ok {
		return e
	}
	if e, ok := m.Specs[id]; ok {
		return e
	}
	if e, ok := m.System[id]; ok {
		return e
	}
	return nil
}

// EntryPath returns the path to the manifest file within the compiled directory.
func EntryPath(compiledDir string) string {
	return filepath.Join(compiledDir, ManifestFile)
}
