package manifest

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/securacore/codectx/core/chunk"
	"github.com/securacore/codectx/core/markdown"
	"github.com/securacore/codectx/core/project"
)

// metadataHeader is the comment header written at the top of metadata.yml.
const metadataHeader = "# codectx compiled metadata\n# Document relationship graph with chunk lists and cross-references.\n# Generated by codectx compile \u2014 do not edit.\n\n"

// Metadata is the top-level structure for metadata.yml.
// It describes every source document with its chunks, token totals,
// and cross-reference placeholders.
type Metadata struct {
	// CompiledAt is the ISO 8601 timestamp of when compilation occurred.
	CompiledAt string `yaml:"compiled_at"`

	// Documents maps relative source file paths to their metadata entries.
	Documents map[string]*DocumentEntry `yaml:"documents"`
}

// DocumentEntry describes a single source document in the metadata.
type DocumentEntry struct {
	// Type is the document type derived from its directory path.
	Type DocumentType `yaml:"type"`

	// Title is the document title, derived from the first H1 heading
	// or the filename stem as a fallback.
	Title string `yaml:"title"`

	// Chunks lists the chunk IDs produced from this document, in sequence order.
	Chunks []string `yaml:"chunks"`

	// TotalTokens is the sum of all chunk token counts for this document.
	TotalTokens int `yaml:"total_tokens"`

	// ReferencesTo lists documents that this document references.
	// Nil until cross-reference extraction populates it.
	ReferencesTo []Reference `yaml:"references_to"`

	// ReferencedBy lists documents that reference this document.
	// Nil until cross-reference extraction populates it.
	ReferencedBy []Reference `yaml:"referenced_by"`
}

// BuildMetadata constructs Metadata from compiled chunks.
//
// It groups chunks by source file, computes per-document statistics,
// derives document types from paths, and extracts titles from chunk data.
//
// The blocks parameter maps source paths to their parsed document blocks,
// used for title extraction (first H1 heading). It may be nil, in which
// case titles fall back to filename stems.
func BuildMetadata(chunks []chunk.Chunk, blocks map[string]*markdown.Document) *Metadata {
	m := &Metadata{
		CompiledAt: CompiledAtNow(),
		Documents:  make(map[string]*DocumentEntry),
	}

	// Group chunks by source file.
	type docAccum struct {
		chunks []chunkRef
		tokens int
	}
	bySource := make(map[string]*docAccum)

	for i := range chunks {
		c := &chunks[i]
		acc, ok := bySource[c.Source]
		if !ok {
			acc = &docAccum{}
			bySource[c.Source] = acc
		}
		acc.chunks = append(acc.chunks, chunkRef{id: c.ID, sequence: c.Sequence})
		acc.tokens += c.Tokens
	}

	// Build document entries.
	for source, acc := range bySource {
		// Sort chunks by sequence within each document.
		sort.Slice(acc.chunks, func(i, j int) bool {
			return acc.chunks[i].sequence < acc.chunks[j].sequence
		})

		chunkIDs := make([]string, len(acc.chunks))
		for i, ref := range acc.chunks {
			chunkIDs[i] = ref.id
		}

		title := deriveTitle(source, blocks)

		m.Documents[source] = &DocumentEntry{
			Type:         ClassifyDocType(source),
			Title:        title,
			Chunks:       chunkIDs,
			TotalTokens:  acc.tokens,
			ReferencesTo: nil, // Placeholder for cross-reference extraction.
			ReferencedBy: nil, // Placeholder for cross-reference extraction.
		}
	}

	return m
}

// chunkRef pairs a chunk ID with its sequence for sorting.
type chunkRef struct {
	id       string
	sequence int
}

// deriveTitle extracts a title for a document. It looks for the first H1
// heading block in the document. If none is found or blocks is nil, it
// falls back to the filename stem (e.g. "jwt-tokens" from "jwt-tokens.md",
// "README" from "README.md").
func deriveTitle(source string, blocks map[string]*markdown.Document) string {
	if blocks != nil {
		if doc, ok := blocks[source]; ok {
			for _, b := range doc.Blocks {
				if b.Type == markdown.BlockHeading && b.Level == 1 {
					return b.Content
				}
			}
		}
	}

	// Fallback: filename stem.
	base := filepath.Base(source)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// WriteTo serializes the metadata to YAML at the given path.
func (m *Metadata) WriteTo(path string) error {
	return project.WriteYAMLFile(path, metadataHeader, m)
}

// MetadataPath returns the path to the metadata file within the compiled directory.
func MetadataPath(compiledDir string) string {
	return filepath.Join(compiledDir, MetadataFile)
}
